a = input ('Digite algo: ')
print('O tipo primitivo desse valor "{}" é: {} '.format(a, type(a)))
print('"{}" Só tem espaços? {} '.format(a, a.isspace()))
print('"{}" É um número? {} '.format(a, a.isnumeric()))
print('"{}" É alfabético? {} '.format(a, a.isalpha()))
print('"{}" É alfanumérico {} '.format(a, a.isalnum()))
print('"{}" Está  em maiúscula? {} '.format(a, a.isupper()))
print('"{}" Está em minúsculas? {} '.format(a, a.islower()))
print('"{}" Está capitalizada? {} '.format(a, a.istitle()))
